// Code generated by protoc-gen-ts_proto. DO NOT EDIT.
// versions:
//   protoc-gen-ts_proto  v2.6.1
//   protoc               v3.19.1
// source: appointment.proto

/* eslint-disable */
import { BinaryReader, BinaryWriter } from "@bufbuild/protobuf/wire";
import { Timestamp } from "./google/protobuf/timestamp";
import { Doctor, Patient, Staff } from "./user";

export const protobufPackage = "com.git_commit_therapy.proto";

export interface Appointment {
  appointmentId: number;
  dateTime: Date | undefined;
  staff: Staff | undefined;
  doctor: Doctor | undefined;
  patient: Patient | undefined;
}

function createBaseAppointment(): Appointment {
  return {
    appointmentId: 0,
    dateTime: undefined,
    staff: undefined,
    doctor: undefined,
    patient: undefined,
  };
}

export const Appointment: MessageFns<Appointment> = {
  encode(
    message: Appointment,
    writer: BinaryWriter = new BinaryWriter(),
  ): BinaryWriter {
    if (message.appointmentId !== 0) {
      writer.uint32(8).int32(message.appointmentId);
    }
    if (message.dateTime !== undefined) {
      Timestamp.encode(
        toTimestamp(message.dateTime),
        writer.uint32(18).fork(),
      ).join();
    }
    if (message.staff !== undefined) {
      Staff.encode(message.staff, writer.uint32(26).fork()).join();
    }
    if (message.doctor !== undefined) {
      Doctor.encode(message.doctor, writer.uint32(34).fork()).join();
    }
    if (message.patient !== undefined) {
      Patient.encode(message.patient, writer.uint32(42).fork()).join();
    }
    return writer;
  },

  decode(input: BinaryReader | Uint8Array, length?: number): Appointment {
    const reader =
      input instanceof BinaryReader ? input : new BinaryReader(input);
    let end = length === undefined ? reader.len : reader.pos + length;
    const message = createBaseAppointment();
    while (reader.pos < end) {
      const tag = reader.uint32();
      switch (tag >>> 3) {
        case 1: {
          if (tag !== 8) {
            break;
          }

          message.appointmentId = reader.int32();
          continue;
        }
        case 2: {
          if (tag !== 18) {
            break;
          }

          message.dateTime = fromTimestamp(
            Timestamp.decode(reader, reader.uint32()),
          );
          continue;
        }
        case 3: {
          if (tag !== 26) {
            break;
          }

          message.staff = Staff.decode(reader, reader.uint32());
          continue;
        }
        case 4: {
          if (tag !== 34) {
            break;
          }

          message.doctor = Doctor.decode(reader, reader.uint32());
          continue;
        }
        case 5: {
          if (tag !== 42) {
            break;
          }

          message.patient = Patient.decode(reader, reader.uint32());
          continue;
        }
      }
      if ((tag & 7) === 4 || tag === 0) {
        break;
      }
      reader.skip(tag & 7);
    }
    return message;
  },

  create(base?: DeepPartial<Appointment>): Appointment {
    return Appointment.fromPartial(base ?? {});
  },
  fromPartial(object: DeepPartial<Appointment>): Appointment {
    const message = createBaseAppointment();
    message.appointmentId = object.appointmentId ?? 0;
    message.dateTime = object.dateTime ?? undefined;
    message.staff =
      object.staff !== undefined && object.staff !== null
        ? Staff.fromPartial(object.staff)
        : undefined;
    message.doctor =
      object.doctor !== undefined && object.doctor !== null
        ? Doctor.fromPartial(object.doctor)
        : undefined;
    message.patient =
      object.patient !== undefined && object.patient !== null
        ? Patient.fromPartial(object.patient)
        : undefined;
    return message;
  },
};

type Builtin =
  | Date
  | Function
  | Uint8Array
  | string
  | number
  | boolean
  | undefined;

export type DeepPartial<T> = T extends Builtin
  ? T
  : T extends globalThis.Array<infer U>
    ? globalThis.Array<DeepPartial<U>>
    : T extends ReadonlyArray<infer U>
      ? ReadonlyArray<DeepPartial<U>>
      : T extends {}
        ? { [K in keyof T]?: DeepPartial<T[K]> }
        : Partial<T>;

function toTimestamp(date: Date): Timestamp {
  const seconds = Math.trunc(date.getTime() / 1_000);
  const nanos = (date.getTime() % 1_000) * 1_000_000;
  return { seconds, nanos };
}

function fromTimestamp(t: Timestamp): Date {
  let millis = (t.seconds || 0) * 1_000;
  millis += (t.nanos || 0) / 1_000_000;
  return new globalThis.Date(millis);
}

export interface MessageFns<T> {
  encode(message: T, writer?: BinaryWriter): BinaryWriter;
  decode(input: BinaryReader | Uint8Array, length?: number): T;
  create(base?: DeepPartial<T>): T;
  fromPartial(object: DeepPartial<T>): T;
}
