services:
  web:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: SA-Vue-Frontend
    ports:
      - "3000:3000"
    volumes:
      - .:/app
    command: ["pnpm", "run", "dev"]
